### ISSUE TITLE
Generating noises on torus-shaped coordinate.

### ISSUE THREAD

**Issue by mars2nico** [Auburn/FastNoise#53]
Sorry don't know where else to ask. Can't find the solution in the Wiki and search results of issues with following keywords.

- 'loop'
- 'repeat'
- 'torus'

I want to a function like this issue's title.

Do someone have any idea to settable to any values with as few modifications as possible?

Although limited values(2^N*) can be configured only(, and many noise/fractal/3D functions not work),
I'm trying to implement the function written on forked repo in my repos. 
* ^ : exponent

Please give me some advise or some comments.

**Comment by Auburn** [comment]
I'm struggling to understand what you are referring to, could you link to one of these forked repos?

**Comment by mars2nico** [comment]
Thanks for your reply.
Here's the information of repos.

Location: `private float SingleSimplex(int seed, FNLfloat x, FNLfloat y)`
Commit: [mars2nico/FastNoise@e4ae91c](https://github.com/mars2nico/FastNoise/commit/e4ae91c588e387b6a7529bb14e9e3f1b2757d189)
Branch: devel
Repos: mars2nico/FastNoise
Function: OpenSimplex (2D)

Location: `private float SingleOpenSimplex2(int seed, FNLfloat x, FNLfloat y, FNLfloat z)`
Commit: [mars2nico/FastNoise@3aa4d4c](https://github.com/mars2nico/FastNoise/commit/3aa4d4c4ac5910e09dda0c996447ca74e04f1bf9)
Branch: ( same above )
Repos: ( same above )
Function: OpenSimplex (3D)

* I'm coding on C#. So otherwise are not exists.
* Using [PreviewApp](https://github.com/Auburn/FastNoise/tree/master/PreviewApp), I confirmed a visual behavior of this library.

**Comment by a-fent** [comment]
If I understand the commit right, it implements the possibility of making periodic noise based on a period of 2^x. Periodic noise was also requested in the original FastNoise library, though the offered implementation had performance implications because it allowed arbitrary integers as periods.

I am very happy to see the overhaul of the lib and would still love to see a periodic/tiling/wrapping/repeating generating function in it.

**Comment by mars2nico** [comment]
@a-fent Thanks for your information.

I seem the implement is equals to its function what you wrote, and I understood why not implemented.
I think so(I seem modulo operation has considerable impact of performance).

I try to see the lib and search with keywords contains periodic/tiling/wrapping.

**Comment by Auburn** [comment]
Tileable noise has been discussed before for FastNoise, the conclusion was that it's out of scope for  what FastNoise aims to provide. Adding it to existing noise functions would slow them down for regular noise generation. Adding a separate set of noise functions for it would bloat the total code size and require API changes, since not all noise types can support this type of tileable noise.

https://github.com/Auburn/FastNoise2 does support tileable 2D generation through the use of 4D noise which works on all noise types.

**Comment by mars2nico** [comment]
Duplicate of #20

**Comment by mars2nico** [comment]
#20

**Comment by mars2nico** [comment]
I see. API changes to be necessary to do it...
I'llto consider to use FastNoise2.
